### ISSUE TITLE
Masthead Docs

### ISSUE THREAD

**Issue by troychaplin79** [ravendesignsystem/rds#10]
https://ravendesignsystem.github.io/rds/docs/blocks/header/masthead/#masthead-with-navigation-and-call-to-action-button

The docs on how to add a button to the masthead are incorrect

It currently shows this code, which is specifically for the hamburger menu:

```
<ul class="masthead__btns">
	<li class="masthead__hamburger">
		<button aria-label="Open Menu" class="c-but-hamburger c-but-hamburger--spin" type="button">
			<span class="c-but-hamburger__box">
				<span class="c-but-hamburger__inner"></span>
				</span>
		</button>
	</li>
</ul>
```

The correct code example to show is:

```
<li class="masthead__button">
	<a class="masthead__button-link" href="#">Button</a>
</li>
```

**Comment by dannybrown73** [comment]
Fixed.
