### ISSUE TITLE
Forms: Select fields need “value” property in examples 

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#101]
In the example markup for select lists on the form page: [https://ravendesignsystem.github.io/rds/dev/components/content/form/](https://ravendesignsystem.github.io/rds/dev/components/content/form/) the value="" is missing. 

Also, if label is defined as a parameter, i'm not sure the Text is needed again in between the <option></option>

**Comment by troychaplin** [comment]
Value examples added to all select list fields that didn't have it.

**Comment by troychaplin** [comment]
Reassigning issue to @mcorkum to clarify or complete the note `Also, if label is defined as a parameter, i'm not sure the Text is needed again in between the`

**Comment by troychaplin** [comment]
Value attributes added to select list examples. Label and text inside the option tag will remain, as all examples of an accessible select list use both. Not 100% clear if it's required, but leaving it in would be better just in case.
