### ISSUE TITLE
Forms: Styling on upload field

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#104]
Currently, the upload field is very basic, using the default browser styles. See below: 

![Screen Shot 2020-03-26 at 2 36 51 PM](https://user-images.githubusercontent.com/1107907/77683760-45b89880-6f6f-11ea-8548-719499f15b0b.png)

This will work for now, and perhaps this was intentional. However, looking at examples from other design systems it seems uploads could be much nicer. See: [https://ant.design/components/upload/](https://ant.design/components/upload/)

**Comment by troychaplin** [comment]
Added an svg icon to improve the design without modifying the basic markup of an upload field. The Ant example hides the default inpout and builds a new one with a lot of additional markup, which i wanted to avoid
