### ISSUE TITLE
Forms: Arrow on select field is misaligned when field label is used

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#105]
The examples on the RDS form page for selects have labels, but they have the class of ```u-visually-hidden```. In the example form I was building, selects needed to have labels. Removing this class results in the arrow for the select dropdown becoming misaligned

See below: 
![Screen Shot 2020-03-26 at 2 42 08 PM](https://user-images.githubusercontent.com/1107907/77684196-00489b00-6f70-11ea-8779-8901d9b6f1d7.png)

**Comment by troychaplin** [comment]
Style issues have been fixed
