### ISSUE TITLE
Accessibility: Add "Skip to main content" in Masthead Block, and ensure Main section has a consistent id

### ISSUE THREAD

**Issue by cudevmaxwell** [ravendesignsystem/rds#107]
**Describe the bug**
The Masthead Block should have an `a` element as it's first child, which has an anchor link to the main content section. That link should be consistently styled on all RDS pages.  

**To Reproduce**
1. Use the base Masthead Block.
2. Try to jump to main content using tab navigation.   

**Expected behavior**
A "Skip to main content" link should appear, which is an anchor link to the first `main` on the page.

**Additional context**
The 'skip link' could also be the first element under `body`.

**Comment by troychaplin** [comment]
Note to self, RDS has this, it exists immediately after the opening body tag as:

`<a class="u-visually-hidden" href="#content">Skip to main content</a>`

This is not reflected on the getting started page, and the base markup example needs to be updated: https://ravendesignsystem.github.io/rds/dev/getting-started/

**Comment by troychaplin** [comment]
The [getting started](https://ravendesignsystem.github.io/rds/dev/getting-started/) documentation has been updated to add the skip to main content link in the basic page markup example

Other items in the doc that have been updated include new links to the CSS and JS resources on CND (referencing only gzip versions)
