### ISSUE TITLE
Need additional styles on forms for validation errors

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#109]
This is what I manually added to the page. Adjust as you see fit

`
 .form__field--error fieldset {
       border: 2px solid #bf112b;

   }

   .form__field--error select {
       border: 2px solid #bf112b;
       background-color: #f9e6e9;
   }

   .form__field legend span.form__required {
       padding-right: 5px;
   }`

**Comment by troychaplin** [comment]
New styles added, will be available in the next release (v 0.19.6 I think)
