### ISSUE TITLE
Docs - Type in code example under Multicol AMA

### ISSUE THREAD

**Issue by cudevmaxwell** [ravendesignsystem/rds#111]
On line [535 of /docs/dev/layouts/multi-column/index.htm](https://github.com/ravendesignsystem/rds/blob/master/docs/dev/layouts/multi-column/index.html#L535) the code example is using the class name `l-multicol--am` when it should (?) be using the class name `l-multicol--ama`.

**Comment by troychaplin** [comment]
Docs fixed, will show up in the next release which should be done later today.
