### ISSUE TITLE
Masthead top nav does not stay in the modal menu on window resize

### ISSUE THREAD

**Issue by cudevmaxwell** [ravendesignsystem/rds#113]
**Describe the bug**
Because `toggleMobileMenu()` in `src/_blocks/masthead/masthead.js` uses the current `offsetWidth` of `querySelector('.c-nav--topnav')`, if the top nav is already appended to the modal menu, the offsetWidth is 0. This means a top nav that is too wide for the current viewport will be placed back into the masthead. 

```js
const navWidth = mastheadNav.offsetWidth + 800; //mastheadNav.offsetWidth could be 0 here
if (window.innerWidth <= navWidth ...
```

In other words, if the masthead is already in 'mobile' mode, a window resize will force the masthead back into the 'desktop' mode, even if the top nav is too wide. 

**To Reproduce**
1. Go to https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/ks/
2. Resize the window width between 1000px and 1500px. 
3. You should see the top nav 'jump' between the modal menu and the masthead. 
4. Resize the window so that the top nav is in the modal menu.
5. Resize the window again. You should see the top menu added back to the masthead, even though it's too long.

**Expected behavior**
On resize, the top nav should stay in the modal menu if the viewport is too small for it's width. 

**Screenshots**

![bug](https://user-images.githubusercontent.com/1489722/85213427-32c62200-b32c-11ea-958e-e0f38ac9331e.gif)

**Additional context**
I'm not sure what the solution should be. We avoid this most of the time by having set breakpoints and known-width top nav items, which isn't a solution for RDS since it must be more flexible. Should the top-nav width be calculated on page load and saved?

**Comment by troychaplin** [comment]
@cudevmaxwell this should be done this week, we started working on a fix for this last week

**Comment by troychaplin** [comment]
Nav issues have been fixed and will be available in the next version release
