### ISSUE TITLE
Need to redo the video icons for both the Card component and listing block

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#12]
I cleaned up a bunch of utility classes, including the u-icon classes and realized it would be best to get away from some of the inline icons, including the play button. 

Both the video variant in the listing block and the card component used this so both video buttons no longer exist.

Can you create a new way with just an inline svg to overlay the play button on both video items.

**Comment by troychaplin** [comment]
@dannybrown73 Both items are updated and have been pushed to the prod docs. The overlay shades were inconsistent from cards to listings, so I decided to remove the `u-overlay` and modifier that was being applied to the video card, and instead added a before pseudo that reflected how it was being done on the video listing block.

This also keeps inline with reducing the amount of additional markup as you go deeper into a block / component, and the overlay is added based on a top level modifier of `c-card--video`
