### ISSUE TITLE
SCSS import files need reviewing

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#14]
A few core blocks are imported in app.scss but not core.scss, and this seemed incorrect to me?

https://github.com/ravendesignsystem/rds/blob/master/src/_themes/core/scss/core.scss
https://github.com/ravendesignsystem/rds/tree/master/src/_themes/docs

Specifically, app has listing and textimg, i assumed those should actually be in core?

I've added them to core for now, we need to review what app is doing, and why it's needed. @dannybrown73 if you can clarify the purpose of app.scss then I can review and try and figure out what changes should be done.

**Comment by dannybrown73** [comment]
This has been cleaned up.
