### ISSUE TITLE
Image banners

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#19]
Right now, when we use the `b-banner--img` modifier, we are forced into having a 60% overlay. Given the requested changes to the [Research Works banner](https://github.com/cuweb/theme-researchworks/issues/1), I think we should remove this, and instead add a `b-banner--img-medium` at 60% to go along with `b-banner--img-light` and `b-banner--img-dark`

**Comment by dannybrown73** [comment]
Sounds good. Go for it.

**Comment by dannybrown73** [comment]
hmmm actually wait. Do you see that image banner as the same block?

**Comment by dannybrown73** [comment]
Also, i don't know/think that block will find its way into RDS

**Comment by troychaplin** [comment]
@dannybrown73 as discussed, this is a custom block, no plans to bring in to core rds
