### ISSUE TITLE
More banner spacing issues

### ISSUE THREAD

**Issue by troychaplin79** [ravendesignsystem/rds#20]
This is something I had to add into FF to fix a spacing issue with RDS.

```
.b-header-banner:not(.b-header-banner--img) + .b-header-search {
	margin-top: -40px;
}
```

Without this code, if the search item exists underneath a text only banner, the margin would be -80, which is way too close to the text itself.

If you want to see an example of this, we should do it after a scrum, just give me a heads up about that so I can setup a demo as I don't wanna push sample code to a devsite for a quick show and tell.

**Comment by dannybrown73** [comment]
Solved with new modifier: `u-block-full--kenobi`
