### ISSUE TITLE
Layout Breakpoints

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#24]
~Now that I'm working with layouts on RW, I'm starting to think the breakpoint for `layout-ma` being at 868 is a little too small, in my testing I think 1024px is a much better breakpoint.~

~I'm suggesting we increase this breakpoint, then review the breakpoints on `layout-am` and `layout-ama` with real content.~

Update: changes made to `layout-ma`, ticket will remain open until we go back and do the same tests on `layout-ama`

**Comment by troychaplin** [comment]
@dannybrown73 next time you're in our office area, stop by and I can show you the difference on the `layout-ma` in RW and I'm sure you'll agree with my suggestion

**Comment by troychaplin** [comment]
@dannybrown73 I increased the breakpoint on `layout-ma` to 1024 as we discussed and reviewed on research works, also made a todo so I can go back and review the break for `layout-ama`

**Comment by dannybrown73** [comment]
Layouts seem sorted out. Closing.
