### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#28]
## Layouts

- `src/_layouts/body` should be moved to `src/_themes/core/layouts/body`
- references to `_layouts.scss` exist in: `src/_themes/core/scss/core.scss` and `src/_themes/hp/scss/hp.scss`
- can't find where `layout.js` is being imported into, is this even being used anymore?

## Overlays

- `src/_layouts/overlays` should be moved to `src/_themes/core/layouts/overlays`
- **NOTE:** scss file that exists in `src/_layouts/overlays` is the most up-to-date version
- references to `modal.scss` exist in: `src/_themes/core/scss/core.scss` and `src/_themes/hp/scss/hp.scss`
- the js is being referenced from `src/_themes/core/js/core.js`

**Comment by dannybrown73** [comment]
These have been moved into the core theme.
