### ISSUE TITLE
Review layout issues

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#31]
@troychaplin79  can you have a look at this layout https://ravendesignsystem.github.io/rds/dev/getting-started/get-started/

specifically, when it breaks at medium mq, and let me know what I am doing wrong, markup-wise.

**Comment by troychaplin** [comment]
@dannybrown73 I would assume the CSS is not up-to-date with the layouts... I checked back on the original pens we did, and this one here worked just fine: https://s.codepen.io/cuweb/debug/zJoXQR

I'll dig deeper today and most likely review, and update the entire CSS structure for layouts

**Comment by dannybrown73** [comment]
Looks fixed.
