### ISSUE TITLE
Issues with Masthead

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#35]
**Describe the bug**
There are two issues that need to be fixed with the Masthead submenus

- [x] Small issue with flickering when switching on mobile
- [ ] On mobile, if only one submenu is used, things break.
- [x] Styles are not working properly for <button> submenus

**Comment by troychaplin** [comment]
@dannybrown73 gonna close this, pretty sure you redid the masthead at least 6 times since this ticket was put in
