### ISSUE TITLE
Spacing on sidenav bg gradient

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#36]
If the 3rd level nav is the last in the list, that gradient bg is incredibly tight, compared to a 2nd level item as the last in a list, the gradient isn’t so tight

![Screen Shot 2019-09-18 at 2 17 44 PM](https://user-images.githubusercontent.com/15524465/65174971-f58cd680-da1f-11e9-8b9a-ed3409e0e527.png)

**Comment by dannybrown73** [comment]
Fixed in v0.12.2
