### ISSUE TITLE
Dividing lines in mobile view

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#37]
When using a multicol-am layout, the divider line between the sidenav and the main content area should not be visible below the small break point.

![Screen Shot 2019-09-18 at 2 25 05 PM](https://user-images.githubusercontent.com/15524465/65175128-41d81680-da20-11e9-9b14-e7ab5f022045.png)

**Comment by dannybrown73** [comment]
Fixed with v0.12.2
