### ISSUE TITLE
Top nav 3rd level indicator

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#38]
If someone is using the top nav, and tried to add a third level item, it does strange things... I know that's someone simply NOT following the rules. I think we should consider doing 2 things:

## 1. Remove the arrow from the second level items via css

![Screen Shot 2019-09-18 at 2 28 50 PM](https://user-images.githubusercontent.com/15524465/65175478-f114ed80-da20-11e9-84e5-64764438f2c6.png)

## 2. Add display none on the 3rd level UL

![Screen Shot 2019-09-18 at 2 29 47 PM](https://user-images.githubusercontent.com/15524465/65175486-f40fde00-da20-11e9-9177-7ec1f97790d5.png)

**Comment by dannybrown73** [comment]
Fixed in v0.13.0 release. Added display none to secondary uls.
