### ISSUE TITLE
Core blockquote styles

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#39]
I find padding on blockquotes to be quite tight, I would suggest we change it to be:

`padding: 15px 25px`

Also, we didn't add any styles for the <cite> tag which is used inside a blockquote to indicate who said the quote.

The following could be used to replace the current block quote styles, on line 188 of _reboot.scss

```
blockquote {
	font-weight: 300;
	font-style: italic;
	border-left: 0.2em solid $red;
	margin: 0 0 25px 0;
	padding: 15px 25px;

	p {
		margin-bottom: 0;
	}

	cite {
		display: block;
		margin-top: 15px;
	}
}
```

![Screen Shot 2019-09-19 at 2 31 26 PM](https://user-images.githubusercontent.com/15524465/65271245-c5f6d080-daea-11e9-8417-96488fd42a58.png)

**Comment by dannybrown73** [comment]
SCSS added to v0.12.2
