### ISSUE TITLE
Text-Image Block: Image to the Left issue

### ISSUE THREAD

**Issue by marceloglacial** [ravendesignsystem/rds#40]
**Describe the bug**
Image to the Left shows a align issue when the text is shorter than text column. 

**To Reproduce**
1. Use a short text on the paragraph inside the `textimg__text` div.

**Expected behavior**
Text alignt to left.

**Screenshots**
Long text (working fine):

<img width="1626" alt="Screen Shot 2019-09-25 at 10 43 06 AM" src="https://user-images.githubusercontent.com/11657599/65611839-63d21b80-df81-11e9-990b-5df7d62b623b.png">

Short text (alignment issue):

<img width="1628" alt="Screen Shot 2019-09-25 at 10 43 39 AM" src="https://user-images.githubusercontent.com/11657599/65611872-70ef0a80-df81-11e9-9ccb-7ca395c5cd72.png">

**Desktop:**
 - OS: MacOs
 - Browser: Chrome / Safari
 - Version: 76 / 13

**Comment by troychaplin** [comment]
@dannybrown73 changes have been made, please take a look and QA https://github.com/ravendesignsystem/rds/compare/429c4ef1fd83...ef7c8c6fdedc

**Comment by dannybrown73** [comment]
Looks good. Change logged here https://github.com/ravendesignsystem/rds/issues/41
