### ISSUE TITLE
v 0.13.0

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#41]
- Fixed: issue with text-Img block where text was aligning incorrectly when a small amount of content was in place - re.  #40

**Comment by dannybrown73** [comment]
- Fixed: the sticky masthead no longer fires if the page is too short or does not have scroll - re. #34

**Comment by troychaplin** [comment]
QA required for #42, attn @dannybrown73

**Comment by troychaplin** [comment]
@dannybrown73 closing this so we clean up issues before creating items to push for a v1.0 release
