### ISSUE TITLE
Revised banner styles

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#42]
I noticed there was repetition in widths in the banner scss file, as well as additional padding that prevented banner content from matching the standard width dictated by the small media query size

- All sizes were changed to use the small breakpoint var instead of being hardcoded as 768px
- Removed unnecessary width constraints (eg: h1 on basic banner) as the width is already being set by the wrapping u-block

## Question

Breadcrumb width was inconsistent between basic banners, and those with bg images. Do we want to allow crumbs to extend beyond the small breakpoint?

## Banner with Images + Opacity

During the refactor commit on Sept 13, the modifiers for light and dark opacity options were removed, while they are still noted in the banner documentation. I assume this was an oversight, so I added them back in.

**Comment by dannybrown73** [comment]
Re. Breadcrumbs pretty easy on this. Part of me wants to not see them wrap, which would likely only occur with really long titles.

Let's restrict them to small BP and then test some deep paths from CU websites to see how things look.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2328234/65755604-72cfdf80-e0e1-11e9-875d-86938e069a59.png">

**Comment by dannybrown73** [comment]
Also, everything else here is good. But let's sort the Breadcrumb thing out before closing.

**Comment by troychaplin** [comment]
@dannybrown73 as per on slack conversation this morning, we'll stick with the small breakpoint for all elements on the banner
