### ISSUE TITLE
Card grid documentation inconsistencies

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#43]
While reviewing the card grid block I noticed some inconsistency in expected behaviour and markup.

- Based on default styles, I assume expected bahaviour is for cards to drop to a 2 column layout at small breakpoint, and adding the `b-cardgrid--stacks`, they would drop to 1 column.
- Both the base example and the stacks modifier example in the docs drop to 1 column, but neither use the modifier.
- In the third example, a 4 column layout, the markup is different (block class on same div as grid class, instead of grid class being a child of block class, as seen in the first 2 examples)
- By default, the 4 column grid drop to 2 column at small breakpoint
- See [Card grid docs](https://ravendesignsystem.github.io/rds/dev/blocks/main/cardgrid/), inconsistencies exist in the "live" examples source code, while the code examples would be correct. Quick overview of this markup on doc page in screenshot.

I wonder if this is an issue with the "live" examples in the docs not being generated correctly, when I look at the [cards twig template](https://github.com/ravendesignsystem/rds/blob/develop/src/_blocks/cardgrid/cardgrid.twig) as well as the base and stacks twig data file, things appear to be configured correctly.

Any ideas?

<img width="575" alt="Screen Shot 2019-09-26 at 8 02 35 PM" src="https://user-images.githubusercontent.com/15524465/65733103-18ac2b80-e09b-11e9-8f81-10c68c68c7b1.png">

**Comment by dannybrown73** [comment]
Working on these docs...

**Comment by dannybrown73** [comment]
**NOTE:** this has pointed out some things that need refactoring. Some HTML is going to change. This should be done either today or tomorrow but if WS is working on the block in the cutheme build you may want to hold off.

Unfortunately, this is part of working with beta software. And with more people testing now we will find other things that need changing. Until we get to v1  anyone working with RDS should expect breaking changes.

I hope anyone working with the system can understand this without frustration. Hopefully, we can get to v1 soon.

**Comment by dannybrown73** [comment]
This was a really old block that hadn't been looked at in a while. Pull down the dev branch and check things out for review.

**Comment by troychaplin** [comment]
Issue has been solved and new documentation has been reviewed
