### ISSUE TITLE
Review: Masthead Block

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#47]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/)
- [File path](https://github.com/ravendesignsystem/rds/tree/master/src/_blocks/masthead)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/block-masthead.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [ ] Tested with the W3C validator and validates
- [ ] Using a service such as tenon.io, review item for accessibility

**Comment by mcorkum** [comment]
There is a problem with multiple line site titles. If applied to a CMS, we have no way of determining the line break. Often systems (not just WP) return options like this as a single string. This will not work for these types of systems, as we have no way to insert <span> tags into site titles. 

This will likely change markup. This should be addressed before further testing.

**Comment by mcorkum** [comment]
There is an issue in Chrome on on Android - the input for expanding the mobile nav menu isn't working. The menu isn't properly expanded, it does work however the second time.

**Comment by mcorkum** [comment]
Issue
Alert is cut off when scrolled out of, and back into view.
Affected platforms
IE11

Issue
Alert jumps when nav hides on scroll
Affected platforms
Mobile

**Comment by mieradi** [comment]
**Issue**
"Menu Is Too Wide" banner cuts off logo
_Affected platforms_
IE11

**Issue**
Name/Logo overlaps menu items when present
_Affected platforms_
IE11

**Issue**
mobile menus have too much padding bottom
_Affected platforms_
mobile

**Comment by troychaplin** [comment]
Closing this as the masthead has been modified so much that testing should be redone once the latest version from GH-113 is completed
