### ISSUE TITLE
Review: Card Grid

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#48]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/blocks/main/cardgrid/)
- [File path](https://github.com/ravendesignsystem/rds/tree/master/src/_blocks/cardgrid)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/block-cardgrid.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [x] Tested with the W3C validator and validates
- [x] Using a service such as tenon.io, review item for accessibility

**Comment by mcorkum** [comment]
As a note - there is already a branch for this, I fixed some docs.

**Comment by mcorkum** [comment]
@troychaplin79 Done
