### ISSUE TITLE
Review: Details Block

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#49]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/blocks/main/details/)
- [File path](https://github.com/ravendesignsystem/rds/tree/master/src/_blocks/details)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/block-details.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [x] Tested with the W3C validator and validates
- [x] Using a service such as tenon.io, review item for accessibility

**Comment by mcorkum** [comment]
Problem with inconsistent tag termination. refs: #61

**Comment by mcorkum** [comment]
Content Guidelines are missing

**Comment by mcorkum** [comment]
Date format looks off under "Dates and Times" - "Date and time format should always be CCYY-MM-DDThh:mm:ss as per W3C"

**Comment by mcorkum** [comment]
Codepen missing on block details

**Comment by mcorkum** [comment]
There seems to be missing mobile styles / breakpoints. Elements are cut off when re-sizing browser (see attached). This block needs to be examined from a mobile first perspective. Ceasing review until this is addressed. @troychaplin79 

![Screen Shot 2019-10-03 at 10 26 05 AM](https://user-images.githubusercontent.com/1107907/66135850-8b039b00-e5c8-11e9-9c9e-e38913e60410.png)

**Comment by mcorkum** [comment]
Considering there will be markup changes, i've had to uncheck the code comparison, w3c, and accessibility checkboxes. Note - these were checked and tested prior to any markup changes. Only changes need to be reviewed.

**Comment by mcorkum** [comment]
@troychaplin79 - block is complete
