### ISSUE TITLE
Review: Text Image Block

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#51]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/blocks/main/textimg/)
- [File path](https://github.com/ravendesignsystem/rds/tree/master/src/_blocks/textimg)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/block-textimg.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [x] Tested with the W3C validator and validates
- [x] Using a service such as tenon.io, review item for accessibility

**Comment by marceloglacial** [comment]
**Issue**
The docs says:  "In general, the amount of text used should be the same height as the image on large screens. This will, of course, differ if you use a large or small block size."

Bottom padding too thin when we using a large block with text shorter than the image height. 

Detected on: Chrome, Firefox and Safari (desktop).

<img width="1242" alt="Screen Shot 2019-10-16 at 2 22 36 PM" src="https://user-images.githubusercontent.com/11657599/66947549-11849780-f021-11e9-93ab-42dcc78d41bb.png">
<img width="1338" alt="Screen Shot 2019-10-16 at 2 26 51 PM" src="https://user-images.githubusercontent.com/11657599/66947559-18aba580-f021-11e9-91e9-450b57cc0b9b.png">
<img width="1341" alt="Screen Shot 2019-10-16 at 2 26 35 PM" src="https://user-images.githubusercontent.com/11657599/66947571-1d705980-f021-11e9-8f1d-3cdb26462a01.png">

**Comment by marceloglacial** [comment]
**Issue:**
Bottom spacing is too big:
https://devsite.carleton.ca/rds-testing/block-textimg.php

Detected on: Chrome, Firefox and Safari (desktop).

**Screenshots**

<img width="949" alt="Screen Shot 2019-10-16 at 2 33 31 PM" src="https://user-images.githubusercontent.com/11657599/66950272-0a13bd00-f026-11e9-89d5-6c5b60455fd1.png">
<img width="1006" alt="Screen Shot 2019-10-16 at 2 24 11 PM" src="https://user-images.githubusercontent.com/11657599/66950274-0a13bd00-f026-11e9-8b8d-5b75217aa21e.png">

**Comment by marceloglacial** [comment]
**Bock Details**

Link to variants: Left image is not working

https://ravendesignsystem.github.io/rds/dev/blocks/main/textimg/#left-image

**Comment by marceloglacial** [comment]
**CodePen**
Everything is broken on CodePen.
https://codepen.io/cuweb/pen/pozdQzK?editors=1000

**Screenshot**

<img width="1319" alt="Screen Shot 2019-10-16 at 3 16 55 PM" src="https://user-images.githubusercontent.com/11657599/66951281-07b26280-f028-11e9-930b-42e04e6b1233.png">

**Comment by marceloglacial** [comment]
Review done. Added some comments.

**Comment by troychaplin** [comment]
-- codepen is fixed, was using very old css and markup
-- spacing issues are a result of using positioning and forcing heights on elements.

Given the way the markup and functionality is intended to be (always having image above content, but underneath heading), this is a necessary evil. Hopefully in a few months time we can official drop IE11 support, as this would be the first block that I would love to rewrite in CSS grid and use template areas to do all that is needed without forcing heights.

**Comment by mcorkum** [comment]
Done!
