### ISSUE TITLE
Review: Alert Component

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#57]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/components/alert/)
- [File path](https://github.com/ravendesignsystem/rds/tree/master/src/_components/alert)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/component-alert.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [x] Tested with the W3C validator and validates
- [x] Using a service such as tenon.io, review item for accessibility

**Comment by mcorkum** [comment]
Error on the component. The H2 in the alert is being affected by the b-content heading rule. There is an override on the background (set to none), but since the component lives within b-content it will always override as the parent rule is too specific. 

![Screen Shot 2019-10-03 at 1 55 26 PM](https://user-images.githubusercontent.com/1107907/66151861-29eac000-e5e6-11e9-9205-155cb9871b33.png)

**Comment by mcorkum** [comment]
Done!
