### ISSUE TITLE
Review: Card Component

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#59]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/components/cards/card/)
- [File path](https://github.com/ravendesignsystem/rds/tree/master/src/_components/card)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/component-card.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [x] Tested with the W3C validator and validates
- [x] Using a service such as tenon.io, review item for accessibility

**Comment by marceloglacial** [comment]
**Card with title and description:**
- The code example doesn't have a description tag.
- The code example has a different image.

**Screenshots:**

<img width="1153" alt="Screen Shot 2019-10-16 at 9 10 05 AM" src="https://user-images.githubusercontent.com/11657599/66922302-c81e5300-eff4-11e9-8a21-20186fdfcf83.png">

<img width="811" alt="Screen Shot 2019-10-16 at 8 08 57 AM" src="https://user-images.githubusercontent.com/11657599/66918406-4c6cd800-efed-11e9-9ad8-7a7cad3950ab.png">

**Comment by marceloglacial** [comment]
**All the cards with shadows**
- Shadow is being cut on resolutions below 1100px;
- Same behaviour on: 
  - Tablet (responsive)
  - Mobile (responsive)
  - Chrome
  - Chrome on iOS
  - Chrome on Android
  - Firefox
  -  Safari
  - Safari on iOS

P.S.: Works fine outside RDS website (last screenshot). 

**Screenshots:**

<img width="816" alt="Screen Shot 2019-10-16 at 9 32 32 AM" src="https://user-images.githubusercontent.com/11657599/66925398-4df0cd00-effa-11e9-8073-e13756d0e62d.png">
<img width="803" alt="Screen Shot 2019-10-16 at 9 32 55 AM" src="https://user-images.githubusercontent.com/11657599/66925399-4df0cd00-effa-11e9-8126-1c796c2bda7b.png">
<img width="422" alt="Screen Shot 2019-10-16 at 9 32 12 AM" src="https://user-images.githubusercontent.com/11657599/66925400-4df0cd00-effa-11e9-90fa-1d95995a1980.png">

<img width="1715" alt="Screen Shot 2019-10-16 at 9 26 40 AM" src="https://user-images.githubusercontent.com/11657599/66925401-4df0cd00-effa-11e9-8ad2-b41a5e8ac064.png">

<img width="1043" alt="Screen Shot 2019-10-16 at 11 42 41 AM" src="https://user-images.githubusercontent.com/11657599/66935596-3e798000-f00a-11e9-851c-6c9776d4a6a1.png">

<img width="499" alt="Screen Shot 2019-10-16 at 9 52 47 AM" src="https://user-images.githubusercontent.com/11657599/66925732-dec7a880-effa-11e9-81a6-dec17cb265a4.png">

**Comment by troychaplin** [comment]
@mcorkum drop shadow and incorrect code example in docs has been fixed, all dist resources have been pushed to devsite for final testing

**Comment by mcorkum** [comment]
Done
