### ISSUE TITLE
Review: Search Form Component

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#60]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/components/searchform/)
- [File path](https://github.com/ravendesignsystem/rds/tree/master/src/_components/searchform)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/component-searchform.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [ ] Tested with the W3C validator and validates
- [ ] Using a service such as tenon.io, review item for accessibility

**Comment by mcorkum** [comment]
Error on SVG - refs #61

**Comment by mcorkum** [comment]
Good except accessibility

**Comment by marceloglacial** [comment]
Typo at the paragraph: "The Search block can be used in the header section and the overlay section. If you are using a search button in you Masthead block (...)" 

Suggestion:  "a search button in **your** Masthead block".

**Comment by marceloglacial** [comment]
Review done.

**Comment by troychaplin** [comment]
Doc page for search block updated, component is used inside that block, so we can consider this review as completed
