### ISSUE TITLE
IE11 Fixes

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#63]
Any issues that were not easily solved in IE11 will be noted here as a comment and we can get together and look at the best way to solve it together.

- Make note of the block/component that still has issues
- Briefly describe the issue

**Comment by mcorkum** [comment]
On the alert block, there is an issue with the top menu covering the alert on scroll down then scroll back up. 

![Screen Shot 2019-10-04 at 9 22 36 AM](https://user-images.githubusercontent.com/1107907/66210728-83a3c680-e688-11e9-813a-cc9354694604.png)

**Comment by mcorkum** [comment]
Masthead block: Problem with masthead title width overlapping navigation. Note, likely needs to be tested with longer titles. 

![Screen Shot 2019-10-04 at 9 23 38 AM](https://user-images.githubusercontent.com/1107907/66210834-bbab0980-e688-11e9-91db-3a0dcc2dec3b.png)

**Comment by mcorkum** [comment]
Masthead block: Problem with secondary menu items spacing top nav issue

![Screen Shot 2019-10-04 at 9 24 46 AM](https://user-images.githubusercontent.com/1107907/66210915-eb5a1180-e688-11e9-96a9-287d1df8e173.png)

**Comment by mcorkum** [comment]
Button text overflow 

![Screen Shot 2019-10-04 at 9 27 32 AM](https://user-images.githubusercontent.com/1107907/66211168-7affc000-e689-11e9-9a96-3fb8fb0496ba.png)
![Screen Shot 2019-10-04 at 9 28 27 AM](https://user-images.githubusercontent.com/1107907/66211170-7affc000-e689-11e9-9def-dc9ab535f4e3.png)

**Comment by mcorkum** [comment]
Images are missing height: auto 

![Screen Shot 2019-10-04 at 10 16 41 AM](https://user-images.githubusercontent.com/1107907/66214654-201d9700-e690-11e9-8f7a-8b843dfc13cf.png)

**Comment by mcorkum** [comment]
/docs/dev/components/alert/

Icons aren't aligned

![Screen Shot 2019-10-04 at 10 43 43 AM](https://user-images.githubusercontent.com/1107907/66216716-f36b7e80-e693-11e9-9425-f0305d04ca11.png)

**Comment by mcorkum** [comment]
Menu pop-up component isn't properly aligned for the "click" versions. The hover version seems to work fine. 

![Screen Shot 2019-10-04 at 11 09 35 AM](https://user-images.githubusercontent.com/1107907/66218580-75a97200-e697-11e9-8067-3bea5bc244a3.png)

**Comment by troychaplin** [comment]
Listing block, svg icons need some work for IE11, heights are way out of sorts

**Comment by troychaplin** [comment]
> On the alert block, there is an issue with the top menu covering the alert on scroll down then scroll back up.
> 
> ![Screen Shot 2019-10-04 at 9 22 36 AM](https://user-images.githubusercontent.com/1107907/66210728-83a3c680-e688-11e9-813a-cc9354694604.png)

@mcorkum this is referenced in issue #70

**Comment by troychaplin** [comment]
> Masthead block: Problem with masthead title width overlapping navigation. Note, likely needs to be tested with longer titles.
> 
> ![Screen Shot 2019-10-04 at 9 23 38 AM](https://user-images.githubusercontent.com/1107907/66210834-bbab0980-e688-11e9-91db-3a0dcc2dec3b.png)

@mcorkum this is referenced in issue #70

**Comment by troychaplin** [comment]
> Masthead block: Problem with secondary menu items spacing top nav issue
> 
> ![Screen Shot 2019-10-04 at 9 24 46 AM](https://user-images.githubusercontent.com/1107907/66210915-eb5a1180-e688-11e9-96a9-287d1df8e173.png)

@mcorkum referenced in issue #70

**Comment by troychaplin** [comment]
> /docs/dev/components/alert/
> 
> Icons aren't aligned
> 
> ![Screen Shot 2019-10-04 at 10 43 43 AM](https://user-images.githubusercontent.com/1107907/66216716-f36b7e80-e693-11e9-9425-f0305d04ca11.png)

CSS for both block and component alerts were reviewed and modified to fix IE11 issues, and allow for better sharing of component inside the block

**Comment by troychaplin** [comment]
> Menu pop-up component isn't properly aligned for the "click" versions. The hover version seems to work fine.
> 
> ![Screen Shot 2019-10-04 at 11 09 35 AM](https://user-images.githubusercontent.com/1107907/66218580-75a97200-e697-11e9-8067-3bea5bc244a3.png)

@mcorkum referenced in issue #70

**Comment by troychaplin** [comment]
> Listing block, svg icons need some work for IE11, heights are way out of sorts

fixed and merged to develop

**Comment by troychaplin** [comment]
All things referenced in this issue have either been resolved, or noted during a follow up IE11 review. This ticket will be closed and final IE11 fixed are being done in issue #70
