### ISSUE TITLE
Missing Layouts / Documents

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#64]
There are no examples of an A-M-A layout in the documentation for testing.

**Comment by mcorkum** [comment]
Also missing the docs/dev/blocks/header/search/ page

**Comment by dannybrown73** [comment]
Re. Search block. It is found under Dialog blocks but the menu was all messed up. This was fixed and pushed to Dev branch.

Locally you can see it here now - http://localhost:3000/docs/dev/blocks/dialog/search/

**Comment by dannybrown73** [comment]
Re. AMA layouts. Is this what you are looking for? https://ravendesignsystem.github.io/rds/dev/layouts/multi-column/#three-column%3A-a-m-a-layout

**Comment by troychaplin** [comment]
> Re. AMA layouts. Is this what you are looking for? https://ravendesignsystem.github.io/rds/dev/layouts/multi-column/#three-column%3A-a-m-a-layout

@dannybrown73 the doc page you reference does not have a live example of the a-m-a layout for us to visually preview in IE11. I'm not sure how to go about creating one with the twig templating structure. Not critical for v1 of cutheme, but something we'll wanna look at sooner than later.

**Comment by troychaplin** [comment]
This will be tested as per issue #74
