### ISSUE TITLE
Missing Nav Dropdown Example 

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#65]
Need an example for testing the second level of the horizontal site-wide Top Nav

**Comment by dannybrown73** [comment]
Do you mean this? https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/#masthead-with-sub-navigation

**Comment by troychaplin** [comment]
@dannybrown73 that's only an image. Can you explain how and where we can modify one of the examples in the doc page to include a drop down so we can look to fix all the issues the masthead has in IE11?

**Comment by troychaplin** [comment]
Note to self, we can add a few options in masthead for proper testing by uncommenting items that exist in `/src/_blocks/masthead/masthead.twig`

**Comment by troychaplin** [comment]
All hidden items were tested in IE11, this ticket is no longer needed. Anything further will be found and fixed as a part of issue #47
