### ISSUE TITLE
Button component text overflow

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#67]
Currently buttons have white-space: nowrap, which causes text to overflow outside the button. 

Is this the expected functionality? 

If the text is cut off, the button will need overflow: hidden to prevent scroll bars. If the text isn't cut off, does the button go to two lines?   

Example with "text-align: center and white-space: nowrap" removed from the component

![Screen Shot 2019-10-04 at 10 57 42 AM](https://user-images.githubusercontent.com/1107907/66217741-da63cd00-e695-11e9-8329-a2dc156a2fef.png)

**Comment by dannybrown73** [comment]
@mcorkum looking at this quickly in the browser...how are you getting what's in your screenshot? I quickly added a long string and things don't wrap like that. Can you share HTML? thx.

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/2328234/66243132-6ba46500-e6d1-11e9-8104-18e57a4cc52e.png">

**Comment by mcorkum** [comment]
This is a problem specific to IE11

**Comment by troychaplin** [comment]
Assuming expected behaviour is to NOT allow text to wrap, I added an overflow hidden to the button to fix a minor issue in IE11
