### ISSUE TITLE
Details block flex fallback

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#69]
Block was written with css grid but there's no flexbox fallback and the block does not render properly in IE11. This needs to be looked at and fixed.

Once completed, check off the todo in issue #70

**Comment by dannybrown73** [comment]
Have a look with the updated autoprefixer and let's re-review. May still need a rewrite?

**Comment by troychaplin** [comment]
Changed the CSS Grid to match up better with flexbox in order to build a fallback for IE11. @dannybrown73 if you want to QA this before it is merged into develop, please recompile using the GH-69 feature branch.

**Comment by dannybrown73** [comment]
@troychaplin79  Looks good. Good job. Merge away.

**Comment by dannybrown73** [comment]
Looks good. Good job. Merge away.

**Comment by troychaplin** [comment]
Changes merged into develop
