### ISSUE TITLE
Do we still need the b-content styles?

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#7]
Or just rely on reboot base styles?

**Comment by troychaplin** [comment]
@dannybrown73 i just made note of this when reviewing other stuff, I'll look at it this week and make a recommendation

**Comment by troychaplin** [comment]
@dannybrown73 i just took a look at this, cleaned up it a bit, but I don't think we can fully get rid of it, it does server a very specific purpose. Let's discuss a few things around this one when we have a few minutes before closing this issue
