### ISSUE TITLE
Issue with new Webpack setup

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#72]
## Issue: production CSS files not minified

When I run `prod` the CSS file that ends up in the versioned folder is not minified and contains source maps.

for reference in: dist > 0.13.0 >. rds-cu.css

**Comment by troychaplin** [comment]
I deleted everything in dist, except changelog, readme and package files, and ran `npm run prod` and everything is being minified as expected.

Just to be sure, I did a second test by deleting my node_modules, and vendor folder, composer.lock and package-lock.json, then clearing composer cache. I reinstalled the composer and package resources, deleted stuff in dist folder again, and ran `npm run prod` and everything worked fine.

**Comment by troychaplin** [comment]
@dannybrown73 i replaced the copy plugin with a file manager plugin, as it allows stuff to run before and after bundle. I am now able to replicate the original dist structure. Best way to test is to delete node modules, reinstall npm packages, then doing npm run prod will clean up the old dist files and generate all the new stuff

I don't see anything else here that needs to be done, unless there's something I'm missing here, this looks good to merge into develop

**Comment by dannybrown73** [comment]
The production CSS is 240k filled with source maps. We'll want those removed.

**Comment by troychaplin** [comment]
Webpack config has been finalized and merged into develop
