### ISSUE TITLE
Accessibility - Menu-pop up

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#79]
Needs Aria Controls

**Comment by troychaplin** [comment]
@mcorkum what part of this needs aria controls? A specific element? Can you please provide more information?

**Comment by mcorkum** [comment]
Similar to the nav menu, hidden content needs to be announced when the action is fired.

Example is here
https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html

**Comment by troychaplin** [comment]
Referenced in #77, keeping all masthead accessibility issues in one spot
