### ISSUE TITLE
Review: Content Block

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#81]
Before we can get RDS to version 1.0, blocks and components require on final review using the following lists. Any relevant notes about this review, whether it be suggestions, specific notes about changes made, or URL references to resources or additional supporting information, please add as a comment.

## Links

The RDS doc link is where you can find the item to be reviewed. The file path is the location in the repo where markdown, scss, js, and data files live.

- [RDS doc page](https://ravendesignsystem.github.io/rds/dev/blocks/main/content/)

## Stand Alone Template

For better accessibility testing and validation, a [template has been created](https://devsite.carleton.ca/rds-testing/block-content.php) using the block that lives outside of the RDS Docs site. If changes are made to the block, this file should be updated and tested again in  tenon and w3c.

## Documentation

The first step is to read the related documentation in its entirety to understand the purpose of the item being reviewed and get a better understanding of its expected bahviour.

- [x] Block is fully documented
- [x] Markup examples are correct as per the written documentation
- [x] Live examples have been checked and matches the expected behaviour
- [x] Source code for live examples has been checked and matches the examples provided

## Browser Testing

- [x] Fully tested in IE 11
- [x] Fully tested in Edge
- [x] Fully tested in Chrome
- [x] Fully tested in Firefox
- [x] Fully tested in Safari
- [x] Fully tested in Safari on iOS
- [x] Fully tested in Chrome on iOS
- [x] Fully tested in Chrome on Android

## Accessibility and Markup

Accessibility should be the main focus of this review, with a minor secondary focus on markup review.

- [x] Tested with the W3C validator and validates
- [x] Using a service such as tenon.io, review item for accessibility

**Comment by marceloglacial** [comment]
**Large Images**
Are not loading.
Detected on: IE11.

**Screenshot**

<img width="1651" alt="Screen Shot 2019-10-17 at 3 14 46 PM" src="https://user-images.githubusercontent.com/11657599/67040212-000ac080-f0f1-11e9-81d5-b064dbc126c6.png">

<img width="1638" alt="Screen Shot 2019-10-17 at 3 09 14 PM" src="https://user-images.githubusercontent.com/11657599/67040368-5d067680-f0f1-11e9-9bee-9916a3923098.png">

**Comment by marceloglacial** [comment]
**Audio**
Unsupported file type.
Detected on: IE11 and Edge.

**Screenshot**

<img width="1656" alt="Screen Shot 2019-10-17 at 3 06 02 PM" src="https://user-images.githubusercontent.com/11657599/67040309-3b0cf400-f0f1-11e9-91aa-1fa7c1b53f02.png">

<img width="1637" alt="Screen Shot 2019-10-17 at 3 10 55 PM" src="https://user-images.githubusercontent.com/11657599/67040335-43fdc580-f0f1-11e9-8b09-5b6b870ec5ee.png">

**Comment by marceloglacial** [comment]
**QA Code**
Needs a break line.
Detected on IE11 and Edge.

**Screenshot**

<img width="1640" alt="Screen Shot 2019-10-17 at 3 11 35 PM" src="https://user-images.githubusercontent.com/11657599/67040523-ace53d80-f0f1-11e9-9e2c-76b146462655.png">
<img width="1641" alt="Screen Shot 2019-10-17 at 3 09 52 PM" src="https://user-images.githubusercontent.com/11657599/67040524-ace53d80-f0f1-11e9-9d7b-82ebe398f4bc.png">

**Comment by marceloglacial** [comment]
Review done.

**Comment by troychaplin** [comment]
- Image reference was incorrect, IE11 ignores srcset, that is what is used on all other browsers.
- Added more content to avoid QA Code issue.
- Audio issues cannot be recreated in my VM, the render and play correctly
