### ISSUE TITLE
Masthead questions / issues

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#82]
Not sure if the code in the docs is out of date, or if I'm just not setting this up properly... but I'm having some issues, and have been working with [this template](https://devsite.carleton.ca/rds-testing/block-overlay.php) for testing purposes

- hamburger icon only shows on mobile, but doesn't do anything when clicked on, even though I see the code in the overlay (but when you click search in mobile, both the search modal AND the menu modal show up)
- top nav doesn't drop to the next line the way it does in the docs
- in top nav, there's an item for "Hover Submenu" that doesn't reveal the menu

**Comment by mieradi** [comment]
There are a few issues that we should review here.  What would the most ideal what to go over this? I could also rewrite the whole thing if that's the best option.

**Comment by troychaplin** [comment]
@mieradi can you add a list of the issues you mention, @dannybrown73 is hoping to jump in and look at this a bit later today
