### ISSUE TITLE
Masthead Requirements

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#83]
The following are the requirements to review/update for the masthead:

## Masthead

- [x] Masthead does not follow the user down the page, it slides back into view when the user begins scrolling back up the page

## Site Title

- [ ] ~~Masthead with long titles: can we add a new modifier to drop titles evenly in 2 lines? this would be important for CMS tools that do not provide the level of control to manually add span tags~~

## Top Nav

- [x] nav should show warning if length exceeds 960 (I think, if I am reading js right)
- [x] nav drops down to the next line when visible space has been maxed out (the point where the nav items would typically wrap
- [x] when nav drops it has horizontal scrolling functionality

## Existing

The following is a list of existing functionality that works fine, but noted here to ensure they continue to function and are tested after other changes are made.

- [ ] Search, login, and hamburger button trigger overlays that exist on the page below the footer markup (currently works fine, just making sure that doesn't break)
- [ ] the main overlay wrapper uses `<dialogue>` and may require a polyfill for browser support (the dialog markup is not part of the masthead, but noting this for the polyfill inclusion and awareness during testing)
- [x] nav items and/or buttons can have submenus, and using an `<a>` will reveal the submenu on hover, while using `<button>` requires a click to reveal the submenu

**Comment by mieradi** [comment]
@troychaplin79 can you elaborate on the Site Title requirement? Just a little confused.

**Comment by troychaplin** [comment]
@mieradi right now, to break a site title on 2 lines you need to wrap part of the title in a span. This won't work in the context of cutheme, so I was planning on looking into any potential ways we could do an automatic 2 line title with CSS.

Because this is something we'll need to investigate for cutheme, and in an effort to finish RDS, I've removed this todo from this list, and once we come up with a solution in cutheme, we can incorporate it back into RDS in a future point version.

**Comment by mieradi** [comment]
@troychaplin79 ok! No worries at all. We can definitely do this, just wanted to clarify.

**Comment by troychaplin** [comment]
@mieradi here's a few bugs to fix

- [ ] if all buttons are removed from the masthead twig file, except search, modal close and navicon, the close functionality no longer works when clicked (comment out lines 46-91 in twig file)
- [ ] after closing the menu modal you can no longer scroll down the page. This seems to be related to some inline styles on body that aren't working in the same way as when you click on the search button

**Comment by troychaplin** [comment]
Closing masthead issues related to functionality as a new issue will be created
