### ISSUE TITLE
Masthead 2.0 - Error message issue

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#84]
Edit// initial with error message issue resolved by removing them.

**Comment by dannybrown73** [comment]
@mieradi noticed another thing right after you removed the warning. I think we might need a resize listener after all. Right now when the masthead buttons collide with the nav, the buttons get pushed off screen instead of the nav dropping - 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/2328234/67787717-6d024c80-fa47-11e9-9d94-ead2f69bcfff.png">

This seems to happen on refresh as well as reload. On resize when there is enough room menu should go back up as per live https://ravendesignsystem.github.io/rds/

**Comment by dannybrown73** [comment]
One more, maybe related because I don't remember it from before. 

When loading on a small screen the banner is too high/hidden.

Might be another casualty of the quick delete done before lunch.

ReferenceError: Can't find variable: toggleMastheadSizeAlert

<img width="497" alt="image" src="https://user-images.githubusercontent.com/2328234/67788585-ff572000-fa48-11e9-8642-75725da723ac.png">

**Comment by mieradi** [comment]
Whoops - deleted the function that detects overflow haha
