### ISSUE TITLE
Masthead: Final JS

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#89]
With the agreed functionality changes, the Masthead block was refactored. Mostly CSS changes, reducing the code a ton but a couple of mark up changes. A lot of whats below has been done but some of the recent JS will need updating to theses changes. Good news it will get slimmed down a bunch with this renewal removing a lot of features.

The **required final changes** to JS are as follows:

**Top Nav:**

- [x] Detect when the top nav area runs out of space, and have the hamburger button show up
and nav exists inside the dialogue area for `modal__menu`.
- [x] On click/tap the sub nav displays but when a second item is clicked the previous submenu needs to be hidden.
- [x] When modal is opened, action buttons should go away and the close button will be visible
- [x] Fade out / fade in on scroll up and down needs to be added back

**Side Nav**
- [x] Requires the ability to 'Expand/Collapse All' in both modal and desktop as per live docs.

**Both Navs**
- [x] Full keyboard navigation on both menus needs to be added. in if the code is shared in the c-navmenu component.  Example of keyboard working `[here](https://cdpn.io/cuweb/debug/abbVpgK)`.

**Comment by troychaplin** [comment]
@dannybrown73 can you please update the todo items in the issue description if I have no captured them properly, or add anything that I'm not thinking about. When you're ok with this, please comment and tag @mieradi to let him know he can jump in. Thanks

**Comment by mieradi** [comment]
> Full keyboard navigation on both menus needs to be added. in if the code is shared in the c-navmenu component. Example of keyboard working [here](https://cdpn.io/cuweb/debug/abbVpgK).

This is markup dictated by tab index

**Comment by troychaplin** [comment]
Things can be tabbed through by default, menus can be expanded with the enter key, then links can be followed with the enter key.

@dannybrown73 I assume this is the behaviour you were after? This is what you showed me for the top nav, and the same works on side nav (tough to tell when outline: none is set in css though)

**Comment by troychaplin** [comment]
Closing masthead issues related to functionality as a new issue will be created
