### ISSUE TITLE
Masthead Issues

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#90]
The following issues were noted during a final QA and require additional work before RDS can go to version 0.14

## General

- [x] _(TC)_ Review classes, make sure no old classes still exist
- [x] _(TC)_ Sticky masthead: make sure its default, add modifier to remove sticky

## Top Nav

- [x] _(MI)_ Video was taken to better explain, see TC for more info

## Action Buttons

- [x] _(TC)_ Action button with drop down doesn’t work
- [x] _(TC)_ Hover on red button has wrong colour

## Modals

- [x] _(MI)_ When opening search, focus should be on input

## Mobile

- [x] _(MI)_ Mobile nav is persistent: Open and close mobile nav, the open search (same with login + nav)

**Comment by troychaplin** [comment]
Note: for modifier for fixed position on masthead, a new utility class for `u-absolute` was added that is available globally. This class would be added to the u-block level element to circumvent the position fixed that is applied to `#id-masthead` by default

**Comment by troychaplin** [comment]
@dannybrown73 this is over to you for final QA

**Comment by dannybrown73** [comment]
There is a js console error on the docs homepage. Can someone have a look?

**Comment by troychaplin** [comment]
> There is a js console error on the docs homepage. Can someone have a look?

@dannybrown73 this will be looked at when #92 has been fixed as we can no longer compile or run a watch task in dev

**Comment by troychaplin** [comment]
@dannybrown73 i just went to look at this, and this is actually something that I think needs to be updated on the nav markup, not in JS... The error related to the mobile close button icon not existing on the page, so I checked things on mobile.

None of the new masthead functionality (topnav moving into the mobile nav when space runs out) is happening here. I'm guessing this is not what we want, and would need to be redone wherever this nav exists in the docs.

**Comment by dannybrown73** [comment]
This is resolved. Old code only on hp.
