### ISSUE TITLE
Block Updates

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#91]
There are a few blocks that were never reviewed as they do not appear in the dev docs table of contents:

~~- [ ] Global Nav - https://ravendesignsystem.github.io/rds/dev/blocks/header/globalnav/~~
- [x] Masthead CTA: white modifier was missed, needs to be added

## Other Stuff

- [x] `<code>` block styling requires fixing

**Comment by dannybrown73** [comment]
@troychaplin79  For now, Global Nav was removed from RDS as it complicated navigation when the top nav was used. We may need to get confirmation from the community but for now, it has been removed.

**Comment by troychaplin** [comment]
> @troychaplin79 For now, Global Nav was removed from RDS as it complicated navigation when the top nav was used. We may need to get confirmation from the community but for now, it has been removed.

@dannybrown73 ok, i assume we'll leave the doc files there for now in the case it gets brought back in the future?
