### ISSUE TITLE
Update WebPack build

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#94]
Can the Webpack Dev script be updated so that the rds-cu.js and .css files that end up in dist also end up in 

Build / Docs / CSS/

<img width="319" alt="image" src="https://user-images.githubusercontent.com/2328234/71089136-2dfe9680-216e-11ea-8c66-6ea3f25a75c2.png">

This will help with local testing.

**Comment by troychaplin** [comment]
Entire webpack setup has been refactored and final test will be for v 0.20.0
