### ISSUE TITLE
Issue with web pack prod script

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#95]
@troychaplin79 over the holidays I updated the new Masthead docs and published a new release.

When I went to publish the docs to GitHub, whenever I ran the `npm prod` command no docs were be transferred from the build folder to prod and then I realized all of the docs were also deleted from the Build folder.

So I went into  https://github.com/ravendesignsystem/rds/blob/master/webpack.prod.js
and it looks to me like  line 20 is set to delete the build files prior to copying them to /docs

I commented it out and everything seemed to work. Can you review that code as I imagine there was a reason for it.

**Comment by troychaplin** [comment]
@dannybrown73 did you follow the proper steps to create a release that i wrote a month or 2 ago? https://github.com/ravendesignsystem/rds/blob/master/RELEASE.md

**Comment by dannybrown73** [comment]
@troychaplin79  yes. No problems with the release. But the prod script needed to properly build docs for publishing was deleting all html files until I uncommented that line.

You might need to update a doc and try and push it with the line uncommented to see. Or maybe find what i did wrong. 

Offhand, do you know why you were deleting the build files for local dev?

**Comment by troychaplin** [comment]
If I remember correctly it was doing a cleanup before regeneration to make sure no old, unwanted files stayed in prod docs.

I’ll review when I get a chance, I had no problem when I first wrote those instructions and did my last release.

**Comment by troychaplin** [comment]
@dannybrown73 I just created version 0.15.5, using a minor scss addition for testing purposes. I followed the release doc line-by-line, and everything was perfectly fine. Once I got the the final section for "Build Docs for Prod", I watched the /build/docs folder get cleaned out, and new docs get generated. This is what I expected to happen, and I had no trouble fully finishing a new release.

**Comment by dannybrown73** [comment]
Ok. This looked like a missing npm modules and is fixed.
