### ISSUE TITLE
Masthead block JS issues

### ISSUE THREAD

**Issue by dannybrown73** [ravendesignsystem/rds#96]
To help test the Masthead block, the following stories were set up in src/blocks/masthead/stories:

Some throw JS errors, mostly due to missing elements so we might need some checks/conditionals in the JS so each Masthead story can be published independently. Noting errors below each link.

- [x] [Base - Title and branding](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/base/) 

Error: TypeError: null is not an object (evaluating 'z.querySelectorAll')

- [x] [Base - Long title and branding](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/long-title/)

Error: TypeError: null is not an object (evaluating 'z.querySelectorAll')

### Buttons

- [x] [Base with search button](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/search/)

TypeError: null is not an object (evaluating 'j.classList') - occurs after closing modal

- [x] [Base with login button](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/login/)

TypeError: null is not an object (evaluating 'j.classList') - occurs after closing modal

- [x] [Base with CTA button](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/cta/)

TypeError: null is not an object (evaluating 'Z.addEventListener')

- [x] [Base with CTA white button](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/cta-white/)

TypeError: null is not an object (evaluating 'Z.addEventListener')

- [x] [Base with CTA with dropdown](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/cta-dropdown/)

TypeError: null is not an object (evaluating 'Z.addEventListener')

- [x] [Base with ALL buttons](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/all-buttons/)

### Top Nav

- [x] [Base with Top Nav](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/top-nav/)

### Side Nav

- [x] [Base with Side Nav](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/side-nav/)

- [x] [Base with Side Nav and all CTA](https://ravendesignsystem.github.io/rds/dev/blocks/header/masthead/stories/side-nav-cta/)

**Comment by troychaplin** [comment]
Errors fixed and RDS v0.16.3 has been deployed
