### ISSUE TITLE
Forms: Remove outline / focus on unwanted elements in chrome

### ISSUE THREAD

**Issue by mcorkum** [ravendesignsystem/rds#98]
Focus seems to be applied inconsistently across elements and browsers. For example see radio buttons in Chrome: 

![Screen Shot 2020-03-26 at 2 06 35 PM](https://user-images.githubusercontent.com/1107907/77681009-1d2e9f80-6f6b-11ea-9845-57fa83510914.png)

In safari, only text inputs have focus. I'm not sure which is correct here

To see this issue, go here: [https://ravendesignsystem.github.io/rds/dev/components/content/form/](https://ravendesignsystem.github.io/rds/dev/components/content/form/) and click into elements using Safari / Chrome side by side.

**Comment by troychaplin** [comment]
@mcorkum According to this (under the keyboard section), the focus is required: https://a11yproject.com/checklist/

**Comment by troychaplin** [comment]
Looked into making outline rounded, but that's not possible. Closing this ticket, focus is a requirement for keyboard navigation
